version: '3.8'

services:
  postgres:
    image: postgres:12
    container_name: temporal-postgres
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
      POSTGRES_DB: temporal
    ports:
      - "5445:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: unless-stopped

  temporal:
    image: temporalio/auto-setup:latest
    container_name: temporal
    depends_on:
      - postgres
    ports:
      - "7233:7233"
    environment:
      DB: postgres12
      DB_PORT: 5432
      POSTGRES_USER: temporal
      POSTGRES_PWD: temporal
      POSTGRES_SEEDS: postgres
      TEMPORAL_ADVERTISED_HOSTNAME: temporal
      TEMPORAL_LOG_LEVEL: debug
      TEMPORAL_NAMESPACE: default
      TEMPORAL_DISABLE_UI: true
    restart: unless-stopped

volumes:
  pg-data:
